### ISSUE TITLE
CONTRIBUTING.md does not tell how to add your fork to the local clones 

### ISSUE THREAD

**Issue by BeckerWdf** [eclipse-ide/.github#15]
https://github.com/eclipse-ide/.github/blob/main/CONTRIBUTING.md
nicely explains how to use oomph to set up your development setup. It also states that one should create a fork on github but it lacks one step: How do I add my fork to my dev environment.

I do it the following way:

1. Copy my forks URL (http or ssh) and on my local clone (of the upstream repo) I add an additional remote "fork" and add my fork's URL there.

I think at least one or two sentences should be added to this file.

**Comment by opcoach** [comment]
Yes you are right ! I will add it in the explanation.

**Comment by BeckerWdf** [comment]
> Yes you are right ! I will add it in the explanation.

Thanks. You can add me as reviewer to your PR.

**Comment by opcoach** [comment]
Ok : see the PR https://github.com/eclipse-ide/.github/pull/16

**Comment by opcoach** [comment]
@BeckerWdf you can review the PR :)  I can not add you as a reviewer (probably a right access)...

**Comment by BeckerWdf** [comment]
> @BeckerWdf you can review the PR :) I can not add you as a reviewer (probably a right access)...

Done.
Thanks for fixing
