### ISSUE TITLE
Create the project page description to contribute to the IDE

### ISSUE THREAD

**Issue by opcoach** [eclipse-ide/.github#5]
**Is your feature request related to a problem? Please describe.**
We should provide a list of the different projects included in the IDE

-  description
- link to the installer setup
- nb of first issues
- ...

**Describe the solution you'd like**
Refered in the main contribution page, it should be displayed in a single table with link inside

**Describe alternatives you've considered**
May be a simple table in the main page 

**Additional context**
Use the content of https://docs.google.com/spreadsheets/d/1dr-R-o9IUDyet5bMAAWg6FIZ-GPNZ0gRgtmd6k8DvRU/edit?gid=0#gid=0

**Comment by opcoach** [comment]
Just a try : 

| Project              | Github URL                               | Readme               | COC | Total Repositories | Java Code Repositories | Deprecated Repositories | Contribution Page        | Active Contributors | Opened Issues | Good First Issues | Contribution Tooling | Pending PR | New Issue Process     |
|----------------------|-------------------------------------------|----------------------|-----|--------------------|------------------------|-------------------------|--------------------------|--------------------|---------------|-------------------|-----------------------|------------|-----------------------|
| [Eclipse Foundation](#eclipse-foundation) | [GitHub](https://github.com/eclipse)      | README.md            |     | 273                | 142                    |                         |                          | 8183               | 146           |                   |                       |            |                       |
| [Eclipse Platform](#eclipse-platform)     | [GitHub](https://github.com/eclipse-platform) | ReadME.md            |     | 24                 | 6                      | 11                      | CONTRIBUTING.md           | 815                | 6             |                   | 112                   |            |                       |
| [EGit](#egit)          | [GitHub](https://github.com/eclipse-egit) | README               |     | 6                  | 2                      | 1                       | EGit Contributor Guide    | 23                 | 0             | Gerrithub           | 115                   |            |                       |
| [JDT](#jdt)           | [GitHub](https://github.com/eclipse-jdt)  | README.md            |     | 8                  | 4                      | 0                       | CONTRIBUTING.md           | 709                | 3             |                   |                       |            |                       |
| [PDE](#pde)           | [GitHub](https://github.com/eclipse-pde)  | README.md            |     | 5                  | 1                      | 1                       | CONTRIBUTING.md           | 209                | 0             |                   |                       |            |                       |
| [Equinox](#equinox)       | [GitHub](https://github.com/eclipse-equinox) | README.md            |     | 8                  | 2                      | 2                       | CONTRIBUTING.md           | 81                 |               |                   |                       |            |                       |
| [EMF](#emf)           | [GitHub](https://github.com/eclipse-emf)  | README.md in repository |  | 4                  | 1                      | 0                       |                          | 2                  | 0             |                   |                       |            |                       |
| [M2E](#m2e)           | [GitHub](https://github.com/eclipse-m2e)  | README.md            |     | 9                  |                        |                         | CONTRIBUTING.md           | 286                |               |                   |                       |            |                       |
| [Oomph](#oomph)         | [GitHub](https://github.com/eclipse-oomph) |                      |     |                    |                        |                         | CONTRIBUTING.md           | 9                  | 0             |                   | 1                     |            | GitHub standard       |
| [Otterdog](#otterdog)      | [GitHub](https://github.com/eclipse-csi/otterdog) | README               |     | 1                  | 1                      |                         | contributing.md           |                    |               |                   |                       |            |                       |

## Project Descriptions

### Eclipse Foundation
The Eclipse Foundation manages a wide range of open-source projects. [Learn more](https://github.com/eclipse).

### Eclipse Platform
The Eclipse Platform is the core framework for the Eclipse IDE. [Learn more](https://github.com/eclipse-platform).

### EGit
EGit is an Eclipse Team provider for Git. [Learn more](https://github.com/eclipse-egit).

### JDT
JDT (Java Development Tools) is part of the Eclipse IDE for Java developers. [Learn more](https://github.com/eclipse-jdt).

### PDE
PDE (Plug-in Development Environment) is a set of tools for developing Eclipse plugins. [Learn more](https://github.com/eclipse-pde).

### Equinox
Equinox is the Eclipse OSGi framework. [Learn more](https://github.com/eclipse-equinox).

### EMF
The Eclipse Modeling Framework (EMF) is a framework for building data models. [Learn more](https://github.com/eclipse-emf).

### M2E
M2E provides integration between Eclipse and Maven. [Learn more](https://github.com/eclipse-m2e).

### Oomph
Oomph simplifies the installation of Eclipse IDEs. [Learn more](https://github.com/eclipse-oomph).

### Otterdog
Otterdog is a tool for managing GitHub organizations using configuration as code. [Learn more](https://github.com/eclipse-csi/otterdog).

**Comment by opcoach** [comment]
Other idea

| Project              | Description | Github URL                               | Readme               | Installer Setup  |  Review |
|----------------------|------------------|------------------------------------------|----------------------|-----|--------|
| [Eclipse Platform](#eclipse-foundation) |  The eclipse kernel [See more](https://github.com/eclipse-platform/eclipse.platform?tab=readme-ov-file) | [GitHub](https://github.com/eclipse-platform/eclipse.platform)      | README.md            |  [Setup](https://raw.githubusercontent.com/eclipse-platform/eclipse.platform.releng.aggregator/master/oomph/PlatformSDKConfiguration.setup)    |  PR |

**Comment by HannesWell** [comment]
> Other idea

I think the reduced information is sufficient. But if that currently has the same information, i.e. the GitHub repo links multiple times.
Since the README is displayed very prominently on GH repos I would skip that column.

In the project column we could/should link the PMI entry. In case of platform it's
https://projects.eclipse.org/projects/eclipse.platform

And we should also consider that many Eclipse projects have more than one repository.
In case of eclipse-platform it's for example
- https://github.com/eclipse-platform/eclipse.platform
- https://github.com/eclipse-platform/eclipse.platform.ui
- https://github.com/eclipse-platform/eclipse.platform.swt

So we should maybe have sub-elements e.g.:
- [eclipse-platform](https://projects.eclipse.org/projects/eclipse.platform)
  - https://github.com/eclipse-platform/eclipse.platform
  - https://github.com/eclipse-platform/eclipse.platform.ui
  - https://github.com/eclipse-platform/eclipse.platform.swt

Or maybe this can be also be made nicely in a table.

And instead of linking the raw setup we could also link the contributing section that has the 'Setup button':
https://github.com/eclipse-platform/eclipse.platform?tab=readme-ov-file#how-to-contribute

Then the target would also be more appealing if one clicks it instead of just copying it.

**Comment by opcoach** [comment]
Yes this is good ideas. Projects and repositories must be distinguished.

**Comment by opcoach** [comment]
I put a sample on my fork here : https://github.com/opcoach/.github/blob/update1/projects.md  for some projects before adding the others

**Comment by opcoach** [comment]
I think we can close this issue. Reopen another one to improve the content.
